### ISSUE TITLE
06.28.2020 Civic Opportunity Project Team Meeting

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#10]
### Overview
Gather all items team members want to propose for this weeks' agenda.

### Action Items
- [x] Item for Abi
   - [x] Review GitHub project cards and align on strategy
- [x] Align on Civic Opportunity required team members #3 
- [x] Align on description verbiage for HfLA recruiting
- [x] Project Imagery - Can we get someone to do this from HfLA?
- [x] Discuss a weekly day/time to meet that will work for everyone

**Comment by abi-a** [comment]
Reviewing and providing feedback on each card
