### ISSUE TITLE
Set up Marketing COP meeting 

### ISSUE THREAD

**Issue by tan-zhou** [hackforla/civic-opportunity#116]
### Overview
We need to set up a weekly meeting for the marketing community of practice so that the marketing people have a scheduled time to meet regularly.
  
### Action Items
- [x] Review existing messaging document
- [x] Draft an email that goes to all people who express interest
- [ ] ~Add Lettuce Meet and Marketing interest form link in the email~
- [x] Set up a recurring meeting that starts on Thursday 2/4 6 PM PST
- [x] Send out the invite emails using civicopportunity@hackforla.org 

### Resources/Instructions
- [Marketing Community of Practice Meeting](https://us02web.zoom.us/j/89152328568?pwd=ejEydFdvYys1NFRGSkpsWUFSYks3QT09
)
- [Marketing messaging document](https://docs.google.com/document/d/1QM8FfScmqUixykckXmB2qG5Y3jY6Tpp_2dDXt8Ez4gA/edit)
- [Marketing Interest form](https://forms.gle/J8nJm6oEeGrzr1Eo8)
- [Response Spreadsheet](https://docs.google.com/spreadsheets/d/1FhRWuCSqmgJ4ZbEqDVNoFLxnh52rOgjFJ4xplULikkw/edit?usp=sharing)
- [Marketing Recruitment Pipelines](https://docs.google.com/forms/d/e/1FAIpQLScDrgJHndp48GUbbpj4mlkbqYM0nuaU0Rr6WojKCXM9k9iNNA/viewform) | [Pipelines Response Spreadsheet](https://docs.google.com/spreadsheets/d/19VBho1i-3kmteCUy-T0SsMu2NdblOblI_s2cVRxdC8U/edit#gid=1886028946)
- [Marketing Meetup event](https://www.meetup.com/hackforla/events/275970293/)

**Comment by rjdoria** [comment]
Interpreting status on Interest Forms
-	Interest Form
o	Connected = already contacted
o	Registered = registered for specific event
o	Attended
	Need to apologize for dropping ball earlier
o	Skip Unable to Contribute, email the rest
o	Levels
	Managed others = Manager level
	Mostly Learning = Coordinator
o	What’s a skill level involved? Decide as a team and then have volunteers self-assign

**Comment by rjdoria** [comment]
Reviewed both Messaging -Marketing and -Civic Opportunity Project documents as well as previous issue related to marketing. I will continue reviewing for proper timeline and content of messaging as I begin drafting the various emails.

**Comment by rfambro2** [comment]
@rjdoria - Your interpretations above are correct! Let us know if you have any notes that come from your review sessions.

**Comment by rfambro2** [comment]
@rjdoria - Bonnie is available today @ 4pm to review messaging

**Comment by rjdoria** [comment]
Verbiage tips (also in messaging document)
-          Subject line and first line of email very important to grab attention
o   Emojiterra.com with concise title
§  Cheer emoji
o   Hi _______,
§  Send individual emails with names
-          Cut down on length as much as possible to maintain engagement
-          Use links on words as much as possible instead of things like register here
o   Make links concise, long links can get skipped over
-          Include call to action early in email
o   Register to event at top of email

**Comment by ExperimentsInHonesty** [comment]
@Bonnie to send out a slack message to the hack for la community letting them know about the new community of practice.  Onboarding here. https://www.meetup.com/hackforla/events/275970293/

**Comment by ExperimentsInHonesty** [comment]
@rjdoria move emails out of document and into the spreadsheet with references about which group they are.

**Comment by tan-zhou** [comment]
@rjdoria will add the list of work he did to set up the Marketing cop meeting in the chronological order

**Comment by rjdoria** [comment]
Timeline
- Assigned 1/21 Thurs, busy Fri
- Sat morning
  - research and review prior messaging documents, busy afternoon/evening
  - Missed Sat 4pm window for follow up / feedback (necessary for Lettuce Meet emails)
- 1/24 Sun Team Meeting
  - Could have had draft ready for Lettuce Meet emails, moved onto Onboarding meeting
- Mon 11am follow up
  - draft ready and reviewed with Bonnie
  - Moved Onboarding agenda and registration to Meetup event
  - Circle back for final sign off on messaging and creating Meetup event
- Mon 3pm follow up
  - Resolved Meetup member status as Assistant Organizer
  - Updated event with image with HfLA logo, ended up picking new photo
  - Signed off on Meetup event and publish
  - Revise email messaging for links to Meetup event, sign off
- 1/26 10am, fire off emails as Scheduled Send

**Comment by rjdoria** [comment]
[Meetup Event](https://www.meetup.com/hackforla/events/275970293/)
