### ISSUE TITLE
Onboard on Civic Opportunity Project

### ISSUE THREAD

**Issue by alexilee** [hackforla/civic-opportunity#122]
### Overview
Read up on existing materials for Civic Opportunity in order to get up to speed on the current state of the project.

### Action Items
- [x] Review project [Wiki](https://github.com/hackforla/civic-opportunity/wiki)
- [x] Read one sheet
- [x] Read issues on Project Management Board
- [x] View Product Development Flowchart
- [x] Join project Slack channel
- [x] Review project OKR document

### Resources/Instructions
[One Sheet Link](https://github.com/hackforla/civic-opportunity/blob/master/Civic_Opportunity_Project_OnePage.pdf)
[Civic Opportunity Project Management Board](https://github.com/hackforla/civic-opportunity/projects/1)
[Product Development Flow Chart Link](https://github.com/hackforla/civic-opportunity/blob/master/Product%20Development%20Flow%20Chart.pdf)
[Civic Opportunity Project OKR Document](https://docs.google.com/spreadsheets/d/15Y3RkkoWC9GPilLF5G8IiS3cLYWs3ZiqtOXp2C--PvM/edit#gid=30376616)

**Comment by rfambro2** [comment]
@alexilee - I added the Wiki to the above Action items list as well. Just an FYI.

**Comment by alexilee** [comment]
Great, thanks for the addition. I will take a look as part of this issue,

**Comment by alexilee** [comment]
I have taken a look at the project Wiki, one sheet, project development flowchart and joined the slack channel. I have also requested access for Civic Opportunity Project Initiatives and the OKR document for review.

Additionally, how should I provide feedback for these documents as I review?

**Comment by rfambro2** [comment]
@alexilee - Can you provide feedback in #64 ?
