### ISSUE TITLE
Discuss software development project with Chris Schmitz that aligns with the opportunity project

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/civic-opportunity#14]
### Overview
Chris Schmitz, a long time participant in the HfLA community, has a concept for a civic minded software project for us to review and discuss.

### Action Items

- [x] Read proposal
- [x] Identify hfla team members that should participate in a round table discussion of the project
- [x] Convene meeting of all appropriate parties
   - [x] Identify next steps

### Resources/Instructions
[Proposal: Diversity Personas](https://docs.google.com/document/d/1c4kDdtmAX_DCwuDK4JwfIMatdEojXIIZDO16ins0qW4)

**Comment by ExperimentsInHonesty** [comment]
@rfambro2  please schedule a time for to meet with Chris. to close the loop.  Potential next steps are:
more research?
iceboxing?
defining for potential future project leads (would need identified stakholder, etc).?

**Comment by rfambro2** [comment]
@ExperimentsInHonesty - Just sent @CSchmitz81 and you a Slack message to try and coordinate next steps.
