### ISSUE TITLE
How will success of this project be measured 

### ISSUE THREAD

**Issue by abi-a** [hackforla/civic-opportunity#16]
### Overview
After reviewing the available cards, I am having a tough time calibrating how we will measure success for each week/month or months 

### Action Items
- [x] I would like to clarify the goals for the month and how we can ensure we are meeting each milestone, so it is made clear to all team members the progress we are making towards the defined goals. We need to discuss this as soon as reasonably possible 

Resources to help facilitate our conversation 
https://medium.com/swlh/goals-vs-milestones-c1dcdbb1c708

**Comment by rfambro2** [comment]
@abi-a - Thanks Abi. I think this is helpful to put into perspective. I can talk to Bonnie about this tomorrow when we meet.

**Comment by rfambro2** [comment]
@abi-a - I'm going to roll this concern into #22. So I will close this one for now.
