### ISSUE TITLE
Setup Special Projects Board

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#20]
### Overview
We need a Project board to manage all of the SP volunteers activities in order to maintain visibility.

### Action Items
- [x] Setup SP board using template project board.
- [x] Add in all notecards for what each column means.

### Resources/Instructions
[Project Template Board](https://github.com/hackforla/.github/projects/2)

**Comment by ExperimentsInHonesty** [comment]
Board installation https://github.com/hackforla/civic-opportunity/projects/2

**Comment by ExperimentsInHonesty** [comment]
Completed adding the explainer cards.
