### ISSUE TITLE
Identify OKRs

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#22]
### Overview
Establish a consensus on Project OKRs and propose a framework meeting these objectives.

### Action Items

- [x] Establish Project Objectives
- [x] Establish Key Results deliverables for each Objective
- [x] Review proposal with team
- [x] Make changes/revisions to the proposal
- [x] Finalize proposal

### Resources/Instructions
[What are OKRs?](https://www.bernardmarr.com/default.asp?contentID=1456)
[Civic Opportunity Project OKRs](https://docs.google.com/spreadsheets/d/15Y3RkkoWC9GPilLF5G8IiS3cLYWs3ZiqtOXp2C--PvM/edit#gid=30376616)
[Civic Opportunity Initiatives](https://docs.google.com/document/d/1s1ZiPiepMi-VEYKqoa93kP8STUnDKCt9LMnF1CXMTTw/edit#)
[OKRs from 100 Automations](https://docs.google.com/document/d/1ZeLLdg8fwkWyr9IRF2UqMRoI94JVGyJrMeU73CmSFa4/edit#heading=h.gn1h1rle7goz)
[BOP WBs and OKRs](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/edit#gid=30376616)

**Comment by rfambro2** [comment]
@ExperimentsInHonesty - I've taken another stab at the OKR doc. Let's review when you have time.

**Comment by ExperimentsInHonesty** [comment]
@tan-zhou refactored document so that each subtask is on its own line.  This is helping with readability.  After reviewing the first task of the KR we were able to define the status of each one and link the WIP to whatever related issue it connected to.  If you can continue this process, we can review the doc again next time we meet.

**Comment by rfambro2** [comment]
Thanks @ExperimentsInHonesty and @tan-zhou . I've gone in and linked more of the existing issues to the Tasks. Several new issues will need to be created for the Tasks. We can discuss today.

**Comment by rfambro2** [comment]
Updated OKR doc will revised template here for review.https://docs.google.com/spreadsheets/d/15Y3RkkoWC9GPilLF5G8IiS3cLYWs3ZiqtOXp2C--PvM/edit#gid=30376616

**Comment by rfambro2** [comment]
- [ ] Rename Initiatives to be shorter
- [ ] Make labels for each Initiative (ex. I: Communities of Practice)
- [ ] Add labels to all issues on the repo
- [ ] Add details from Initiatives page to Wiki

**Comment by rfambro2** [comment]
The OKRs will need to be revisited and expanded upon throughout the life of the project.

**Comment by patrickm-tan** [comment]
no longer relevant
