### ISSUE TITLE
Setup initial issues and milestones

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#23]
### Overview
We need to make initial issues and milestones to cover all the proper processes for this project so that we focus on running fast and recruiting.

### Action Items
- [x] Reconcile our current issues with the issues from 100 Automations initial issue templates.  Use this [spreadsheet](https://docs.google.com/spreadsheets/d/1KfBKuUojgSZRMsNcsrEN7x88qVc8dcY-uuwebcZAEB8/edit#gid=900068061)

### Resources/Instructions
[Product Management Process & Onboarding](https://github.com/hackforla/product-managment/issues/7)

**Comment by ExperimentsInHonesty** [comment]
@rfambro2 When we get our next meeting scheduled let's go over this [spreadsheet ](https://docs.google.com/spreadsheets/d/1KfBKuUojgSZRMsNcsrEN7x88qVc8dcY-uuwebcZAEB8/edit#gid=900068061) and reconcile it with all open issues, and determine which other issues we need to create.  We will also need to create any of the appropriate milestones as well.

**Comment by ExperimentsInHonesty** [comment]
Milestones https://github.com/hackforla/civic-opportunity/milestones
