### ISSUE TITLE
Google Analytics and Mixpanel Modeling Analysis

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#35]
### Overview
Understand how GA and Mixed Panel is used for the creation of materials.

### Action Items

- [x] Reach out to @ John Ritchey to get understanding of how GA Model is setup for 311 Project
   - [ ] Document Process
- [ ] Champion the creation and delivery of workshops to educate other teams on getting this setup

**Comment by ExperimentsInHonesty** [comment]
I posted the following in the #ops channel 
@John Ritchey @Naomi Chao introducing the two of you to eachother.  Naomi is going to model the way that your project has setup GA and Mixpanel, to see if we can’t make a project guide for doing that across projects.  The Hack for LA website would be the project that she tests the setup instructions on.  Please make appropriate introductions to whoever on your team can help with this.

**Comment by rfambro2** [comment]
@naomiec - Bonnie mentioned that you have a meeting set up w/ John. Can you note the time here in the issue?

**Comment by naomiec** [comment]
Naomi / John meeting 8/19 @7pm PST

**Comment by rfambro2** [comment]
Wonderful!

**Comment by naomiec** [comment]
1. Had a call with John Ritchey and his UX team, they went over what they were using/what features were most helpful from GA, Mixepanel, and Hotjar
2. Implementation wasn't discussed as much, seems like something that's more of a "watch a youtube tutorial and come up with documentation from there" kind of thing
3. It might take me a while to watch tutorials/tinker around with the tools myself before I can have a final draft of the documentation ready
4. There doesn't seem to be a huge rush, so maybe give me a week?

**Comment by ExperimentsInHonesty** [comment]
If we need a guide to using GA, there are already two issues in progress.


https://github.com/hackforla/product-management/issues/73
https://github.com/hackforla/website/issues/1730
