### ISSUE TITLE
Brigade Organizer's Playbook (BOP) Management

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#38]
### Overview
Hack for LA and Code for America are updating the Brigade Organizers Playbook

### Resources/Instructions
[Brigade Organizers Playbook current version](https://docs.google.com/document/d/1G_v53fGyHqdZNmXkDxqhqkzT7q2TBZ9Xmh9JkWtFQ8Y/edit)
[BOP Extension Plan notes](https://docs.google.com/document/d/1p_3Yv0EZ4UJuMktbTJsCHudUOhBG1s3HO_ffDgmcXF4/edit#)
[GitHub Repository](https://github.com/codeforamerica/brigade-playbook)
[CfA Google Drive for BOP working group](https://drive.google.com/drive/u/0/folders/1ZD1N7oQkuPyafSqDGUF77-EozyUz1y8Q)

### Related Issues
[Set up Calendly](https://github.com/hackforla/civic-opportunity/issues/33)

**Comment by ExperimentsInHonesty** [comment]
This responsibility has been moved to the BoP team and repository https://github.com/hackforla/brigade-playbook
