### ISSUE TITLE
Western Regional Call

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#48]
### Overview
We need to setup a Western Region call for all Brigades in our Region.

### Action Items

- [x] Draft a message about having a monthly Western Region call (Setup a Google Doc in the Special Projects folder and link it to Resources below. This should be a poll that asks about Meetup times - 8am Wednesday, 6pm Friday, 4pm or later Saturday, 4pm or later Sunday. Purpose of poll is create a monthly Western Region call)
   - [x] Get Bonnie to sign off on message
- [x] Sign up for CfA Slack slack.codeforamerica.org
   - [x] Join #brigade channel
   - [x] Join #west-brigades channel
- [x] Post message in West brigades channel
- [x] Update spreadsheet with West brigade member handles
   - [x] Invite members to West brigades channel (Annotate sheet)

### Resources/Instructions
[West Region Contact Directory - HfLA version](https://docs.google.com/spreadsheets/d/12uNxqK9ZCrXuZzRJF1NSZVqkiSEcqU4YTC8WxHVHI8Q/edit)
[Google Drive for Special Projects](https://drive.google.com/drive/u/0/folders/1llFOxKuVL5cgqMQmuCjoNpgksKyEIyp6)

**Comment by naomiec** [comment]
- Sent poll in #west-brigades in Slack. DMed brigade leaders who aren't already in west-brigade with a link to the channel. 
![Western Call Poll Final](https://user-images.githubusercontent.com/31399879/90300210-47b3c300-de4e-11ea-99ae-aa1cb09b8094.jpg) 
- Updated Brigade Contact Directory spreadsheet with Western brigade leaders' Slack handles

**Comment by naomiec** [comment]
Sent out email and slack followup messages to brigade leaders who hadn't voted by 8/16.

**Comment by rfambro2** [comment]
Awesome! Thanks @naomiec

**Comment by rfambro2** [comment]
https://cfa.slack.com/archives/C9FSUR6JE/p1597430743001600

**Comment by ExperimentsInHonesty** [comment]
Document with scripts for messages sent https://docs.google.com/document/d/1r-9xhqaGq2trkLJE5kxjNUDohJf2b6Jm51OoJ5dCNpQ/edit
