### ISSUE TITLE
Post Marketing Director Position on Volunteer Match/Linkedin

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#59]
### Overview
This description will be used for posting on LinkedIn.

### Action Items
- [x] Ray
   - [x] determine which is most current
- [x] Bonnie
   - [x] Get access to volunteer match
- [x] Snigdha
   - [x] Document this process (below in the issue).
     - [x] post on volunteer match
        - [x] review with Bonnie
     - [x] figure out how to make it post on linkedin
- [x] edit the Marketing Role Description doc, Volunteer Match section to be formatted for Volunteer Match specifically, including any constraints.  
     - [x] Update the Marketing Role Descriptions doc with the updated information from Volunteer Match

### Resources/Instructions
[Writeup in issue #3](https://github.com/hackforla/civic-opportunity/issues/3#issuecomment-663922272)
[Marketing Role descriptions](https://docs.google.com/document/d/1SQvBa8ctXJO78_ryiY5ejIBE3V7PDfA5n9A66j-3Ars/edit#heading=h.w3j8f3rqex71)
[instructions for adding job posting to linkedin from volunteer match](https://vmhelp.zendesk.com/hc/en-us/articles/215343787-Connecting-your-opportunities-to-LinkedIn)
[Volunteer Match Job Post constraints](https://docs.google.com/document/d/16EKuUwxIk1v5gVCPs-R21I5h7yCZKfAdoTCTIZnAtGQ/edit?usp=sharing)

**Comment by rfambro2** [comment]
See LinkedIn section of Marketing Role Definitions doc for final descriptions:

**Comment by ExperimentsInHonesty** [comment]
Tom added me to the account and I received the following email:

VolunteerMatch Notification <support@volunteermatch.org> via sendgrid.net
--
to: | bonnie@hackforla.org
date: | Aug 5, 2020, 7:11 PM
subject: | Welcome to VolunteerMatch
mailed-by: | sendgrid.net
signed-by: | sendgrid.net
security: | Standard encryption (TLS) Learn more
: | Important according to Google magic.

Hello Bonnie,

Welcome to VolunteerMatch! You've been added as an administrator for the
following Organization: Code for America

To access your account, go to https://www.volunteermatch.org/post/ and then
enter your email address and password.

If you forget your password, go to
https://www.volunteermatch.org/post/password_request.jsp to request a
temporary replacement and establish a new permanent password..

We look forward to helping you recruit enthusiastic and talented
volunteers!

Sincerely,
The VolunteerMatch Team

P.S. To get the most out of your account, we recommend that you visit our
Learning Center.  You can register for free online trainings on running a
great volunteer program and so much more!
http://learn.volunteermatch.org

Feel free to contact the Community Support Department at
support@volunteermatch.org  with any questions or concerns.

**Comment by ExperimentsInHonesty** [comment]
We have a posting on volunteer match for foodoasis.  We want to make sure we don't overwrite it or accidentally publish it to linked:  https://www.volunteermatch.org/search/opp3281725.jsp

**Comment by ExperimentsInHonesty** [comment]
1. login
2. Add an Opportunity

**Comment by ExperimentsInHonesty** [comment]
@ssuvarna1234 please put all the names of the fields and their constraints (e.g., length, number of selections, etc.)  from volunteer match into a document, it would make it easier for us to setup our posts later, and digitize the process.

**Comment by ExperimentsInHonesty** [comment]
Here is the link to what finally got posted https://www.volunteermatch.org/search/opp3313120.jsp

**Comment by ExperimentsInHonesty** [comment]
It posts automatically to linkedin from volunteer match, but its not showing up yet, so we will check daily until it does. https://www.linkedin.com/jobs/search/?f_C=660862&geoId=92000000

**Comment by ssuvarna1234** [comment]
@ExperimentsInHonesty Here is the [document](https://docs.google.com/document/d/16EKuUwxIk1v5gVCPs-R21I5h7yCZKfAdoTCTIZnAtGQ/edit?usp=sharing) that lists all the fields and constraints for the VolunteerMatch Opportunity Form

**Comment by ExperimentsInHonesty** [comment]
@ssuvarna1234 I have updated the [Marketing roles description doc](https://docs.google.com/document/d/1SQvBa8ctXJO78_ryiY5ejIBE3V7PDfA5n9A66j-3Ars/) by adding some new areas and reorganizing the titles a bit.  There is an asterisk * in front of any section that needs updating

**Comment by ExperimentsInHonesty** [comment]
it showed up in two days: https://www.linkedin.com/jobs/view/2151601151

**Comment by rfambro2** [comment]
@ssuvarna1234 - Do you have a status update on this one?

**Comment by ExperimentsInHonesty** [comment]
I have an interview scheduled today with candidate and I have received a notification of the listing expiring.  I have to address the notification.

**Comment by ExperimentsInHonesty** [comment]
[screencapture-volunteermatch-org-s-auth-activity-2020-09-15-13_41_15.pdf](https://github.com/hackforla/civic-opportunity/files/5228188/screencapture-volunteermatch-org-s-auth-activity-2020-09-15-13_41_15.pdf)
![screencapture-volunteermatch-org-s-auth-activity-2020-09-15-13_41_15](https://user-images.githubusercontent.com/37763229/93262570-4df0d400-f759-11ea-84f2-3aa5ef36e38e.png)
