### ISSUE TITLE
Create Google Doc to Track Project Initiatives

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#63]
### Overview
We need a separate Google Doc to keep track of initiatives.

### Action Items

- [x] Create Doc
- [x] List/Ideate Initiatives
- [x] Evaluate Initiative Value/Lift
- [x] Select Final/Critical Initiatives and use this list to inform OKRs

### Resources/Instructions
[Civic Opportunity Project Initiatives](https://docs.google.com/document/d/1s1ZiPiepMi-VEYKqoa93kP8STUnDKCt9LMnF1CXMTTw/edit#)

**Comment by ExperimentsInHonesty** [comment]
@rfambro2 we added some new fields to the initiatives doc for value and lift.  Let's define them there.

**Comment by rfambro2** [comment]
@ExperimentsInHonesty - Great. Let's discuss today. I've added descriptions for each initiative. We can talk about how this can be developed into value/lift.

**Comment by ExperimentsInHonesty** [comment]
@rfambro2 will can review the doc after you do another round of edits.

**Comment by rfambro2** [comment]
@ExperimentsInHonesty - This doc is ready for review.
