### ISSUE TITLE
Monitor results of UXR form

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/civic-opportunity#65]
### Overview
We need to communicate with the potential UXR volunteers in a timely way so that we can funnel them into the appropriate onboarding and projects.

### Action Items
- [x] Montor the form responses
- [x] Discuss with team members how to respond
- [x] Respond to people who add themselves.
- [x] Add notes in this issue until we are ready to make a process document for it.  

### Resources/Instructions
- [UXR Interest form](https://docs.google.com/forms/d/1r0jFVlVfp8DeARc1LOpXip5WMxXvm5t40pn9p9sgvKQ/edit#response=ACYDBNhpe3zwPLGA7hgNfIQBFDeGbxRf6jEpAeUDqAO3X3FaH2-kmghQBvdZlcnG_Cgm7oI)
 - [Project Recruiting Current Needs spreadsheet](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
Kristin was invited to fill out the form on Saturday (which she did).  Her response was all opportunities.  When I reviewed the HfLA opportunities to find one to put her on, it turns out that the PMs are not being specific enough.  Next action item is Bonnie creates an issue in the product-management repo to  get them to update the current recruiting spreadsheet.

**Comment by ExperimentsInHonesty** [comment]
We need to change the way we present the opportunities to be each its own question so that each one is in a separate block
We will have to copy the current spreadheet to back it up.  Then change the questions, and move the answer into each column where they will now apply.

Rough draft

Which project(s) are you interested in? Please select all that apply. 

LA City Department of Neighborhood Empowerment Design Thinking Group Workshop (https://empowerla.org/redesign/) 
 workshop training: 9/22 6-9PM PDT; workshop 9/29 6-9PM PDT
- [ ] YES

Code for America (CfA) Brigade Organizers UX Interviews (https://bit.ly/3h9K8Xu) Start date: 10/1/20
- [ ] YES

Less time-sensitive projects can be found here: www.hackforla.org/?looking=UI/UX. 
Other:

**Comment by ExperimentsInHonesty** [comment]
I revised the form and moved the answers into the new questions.  I also changed the answers to YES, so that the form would be easier to use when calculating the results.

**Comment by ExperimentsInHonesty** [comment]
Removed the following text:

> LA City Department of Neighborhood Empowerment Design Thinking Group Workshop (https://empowerla.org/redesign/) Workshop training: 9/28 6:30-9PM PDT; Workshop 9/29 6-9PM PDT 

since event has passed

Also changed this: 

> Hack for LA is recruiting for a variety of UX roles on one-time or ongoing projects with partners including www.codeforamerica.org and www.empowerla.org.

to this:
> Hack for LA (HfLA) is recruiting for a variety of UX roles on ongoing HfLA projects and with partners (currently www.codeforamerica.org)

**Comment by ExperimentsInHonesty** [comment]
Also updated this to include training dates
Code for America (CfA) Brigade Organizers UX Interviews (https://bit.ly/3h9K8Xu) Training Dates: training: 10/12 8:00-10AM PDT and 10/14 6:00-8PM PDT

**Comment by rfambro2** [comment]
We've updated the form to remove the Training dates. We've also added information in an auto-response with information on our Meetup events.
