### ISSUE TITLE
Volunteer Recruitment: Product/Project Manager Interest Form

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#74]
### Overview
We need to identify and recruit Product/Project Management volunteers for current and future HfLA projects.

### Action Items

- [x] Create Product/Project Management Google Interest form in Role/Recruitment Folder. Attain the following information in the questionnaire:
   - [x] Contact Info
   - [x] Timezone
   - [x] Availability
   - [x] Project/Position Interests
   - [x] Experience Level
   - [x] Specific tool knowledge
- [x] Review the details about each ask with teammates and make necessary edits
- [x] Discuss with the team on how to respond

### Resources/Instructions
[Role/recruitment folder](https://drive.google.com/drive/folders/1LLqovq883cgU2n-yt8YsnoFlUUp4olgb)
[Product/Project Management Interest Form](https://docs.google.com/forms/d/e/1FAIpQLSem_E3RNQClghm8noHfnEUtwNJaim391MTtxs80zqHA-HCiCg/viewform)
[Project Recruiting Current Needs spreadsheet](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0)

**Comment by rfambro2** [comment]
@ExperimentsInHonesty @tan-zhou - Here's a first stab at the PM Interest Form. Let me know your initial thoughts:

**Comment by ExperimentsInHonesty** [comment]
@rfambro2 please provide a link to the edit form

**Comment by rfambro2** [comment]
@ExperimentsInHonesty - Edit Form can be found here:

https://docs.google.com/forms/d/1eI0_zALzNGYAw7kBLrvZVGL-8w-NVmY5T4L6gCbuJjQ/edit

**Comment by rfambro2** [comment]
I will send out a message to the Product School today and socialize the Interest Form. Once completed, I'll post my outreach message here for documentation.
