### ISSUE TITLE
HfLA Project Marketing Coordinator Fulfillment

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#77]
### Overview
We need to confirm the need for a Marketing Coordinator/Manager on all HfLA Projects.

### Action Items 
- [x] Reach out to Project Leads on Slack and ask if they would like to recruit a Marketing/Communications team member for social media management
- [x] Get a specific understanding of each project need for this role
- [ ] Reach out to the necessary parties to get project SEO needs updated on the HfLA website accordingly 

### Resources/Instructions
[Marketing and Communications Professional Interest Form](https://forms.gle/J8nJm6oEeGrzr1Eo8) 
[Marketing Recruitment Pipelines](https://docs.google.com/spreadsheets/d/1-3dim1QogwYpHogQQ7Yd4rlMEHiOWuCK5Jx3yEkDGiE/edit#gid=0)

**Comment by tan-zhou** [comment]
I updated the Marketing Interest form link used here. The previous link was to the editing version and would tell people to request access.

**Comment by rfambro2** [comment]
@tan-zhou - Thanks Tan

**Comment by tan-zhou** [comment]
@rfambro2 We made some edits to the project section of the form at Sunday's meeting. Bonnie pointed out that some of the descriptions are not accurate (Heart, Home Unite Us, LA TDM Calculator, Lucky Parking, ) Please verify with project managers that 

- the one-line descriptions are adequate representations of the projects 
- links are pointed to projects' own websites if they have one
so we can share this form on Linked in ASAP.

**Comment by ExperimentsInHonesty** [comment]
We will recruit for all projects that responded and even those that didn't with the language we have now.  See issue #76
