### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/civic-opportunity#9]
### Overview
Update the readme file so it is easy for new people joining to get up to speed

### Action Items
- [x] Review the readme file and identify what information is needed and applicable (put notes in comments below)
- [x] Review the project one sheet and identify which of that information belongs in the readme.
- [x] Apply changes to readme.

### Resources/Instructions
[Civic Opportunity One Sheet](https://docs.google.com/document/d/1E4JIMNX9GgD_VcLqcnJCmR8kCnVi1GmgKCoKH9H71Cs/edit#)
[Civic Opportunity Repository Readme](https://github.com/hackforla/civic-opportunity/blob/master/README.md)

**Comment by rfambro2** [comment]
@ExperimentsInHonesty I've updated the ReadMe description. Let me know if you believe more information should be added.

**Comment by ExperimentsInHonesty** [comment]
@rfambro2 here are my edit suggestions:

- Under project context change the google drive link to be the words "Civic Opportunity Project One Sheet" and then link it.

- Under Technology used change Github to be
GitHub: Project Management board  [and then link it]
Slack: #civic-opportunity [link it]

- Under How to Contrib...
Join the team: reach out to Ray (our Product Manager).   The roles we are currently looking to fill are:

[Remove all content starting at Installation Instructions]

**Comment by rfambro2** [comment]
@ExperimentsInHonesty - I've made these updates. Please review.

**Comment by ExperimentsInHonesty** [comment]
@rfambro2 I made some edits and approved the pull request.  Then when I was doing the About (to the right of the readme on the same page), I had to edit to fit, but it also ended up being a content edit.  

Here is what I edited it into.  Please edit yours to match.
The Civic Opportunity Project will seek to provide a curated journey for Civic Tech volunteers. Our goal is to equip participants with the resources, exposure and toolsets to excel in a competitive workforce. The project will continuously iterate the experience process and ultimately exist as software that can be streamlined, scaled and replicated.

**Comment by rfambro2** [comment]
@ExperimentsInHonesty - I updated the ReadMe "About" section to reflect the updated wording.

**Comment by ExperimentsInHonesty** [comment]
@rfambro2 please update the readme to connect to the pdf instead of the google doc.

**Comment by ExperimentsInHonesty** [comment]
Fixed by PR #15
