### ISSUE TITLE
Get feedback on UX Google Form Questionnaire

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#98]
### Overview
We need to recruit UX Researchers for the BOP and TDM Calculator projects. A review of the outreach questionnaire needs to be done so that we can begin to automate the evaluation process.

### Action Items

- [x] Tan to reach out to Mari to get feedback on questionnaire design

### Resources/Instructions
- [UX Interest Form](https://docs.google.com/forms/d/e/1FAIpQLSfJPPz6ASuBVKAvRg0f7WDUuDXVpooqA8rmaDwv-4OUcfrWOw/viewform)
- [Marketing Interest Form](https://docs.google.com/forms/d/e/1FAIpQLSceuQ7Ego657mLimqAhHgeOQCWhlPngDGbg0NzL_XX_j9bVIA/viewform)
- [UX Recruitment Pipelines](https://docs.google.com/spreadsheets/d/1TuDelZ_pCg1pc9murZaYMsnv7CgEwXvoVtH5Jkt32XM/edit#gid=0)

**Comment by tan-zhou** [comment]
I reached out to Mari. Here is her recommendation for the BOP project.
List of UX skills: 
- Conducting Interviews 
- Survey design and analysis 
- Usability testing 
- Prototyping 
- Visual Design
- Coding and tagging qualitative data
- Quantitative analysis Tool (R, Python, or SPSS)
- Texting Mining
- UX Writing
- Accessibility testing
- Front-end programming

The last two items are of less importance at this stage.

**Comment by tan-zhou** [comment]
I added the link to the previous UXR interest form and Marketing interest form for reference.

**Comment by tan-zhou** [comment]
@ExperimentsInHonesty will reach out to Sanjana and provide details on the TDM project

**Comment by rfambro2** [comment]
@tan-zhou - Were we able to integrate Mari's skill recommendations into the Form? Can we close this issue?

**Comment by ExperimentsInHonesty** [comment]
@tan-zhou will update the form to include the additional skills.

**Comment by ExperimentsInHonesty** [comment]
The opportunities will come from: https://github.com/hackforla/UI-UX/projects/2

**Comment by ExperimentsInHonesty** [comment]
@tan-zhou sorry to bug you, but it turns out we need this asap.  I know you are on vacation.  What is your expected ETA on this.  I could get someone to help with it.

Bonnie

**Comment by tan-zhou** [comment]
@ExperimentsInHonesty Thank you for letting me know Bonnie. I will get this done by 2/6. I'll update you once it's ready for review.

**Comment by Olivia-Chiong** [comment]
@tan-zhou go enjoy your vacation. I'm working on it and will be done really soon.

**Comment by tan-zhou** [comment]
> @tan-zhou go enjoy your vacation. I'm working on it and will be done really soon.

Thank you Olivia. I just reordered the list of skills. It looks good!

**Comment by Olivia-Chiong** [comment]
@tan-zhou @rjdoria @rfambro2 Is anyone able to help with posting of this message in [the pipelines](https://docs.google.com/spreadsheets/d/1TuDelZ_pCg1pc9murZaYMsnv7CgEwXvoVtH5Jkt32XM/edit#gid=0)? We urgently need to start the UX recruitment process and it would be good for this to go out sooner than later. Please let me know asap if you will be taking this on.

(Volunteer Opportunity) Hi UX Researchers, UX Analysts and UX Program Designers! Hack for LA (https://hackforla.org/) is looking for people to work on civic tech projects. Come volunteer with us as we attempt to change the world one project at a time. There are both junior and senior roles available for you to contribute to meaningful projects. You don't have to be based in LA as we are operating remotely and welcome talent from around the world. Our next onboarding is Friday 2/12 from 12 - 2 pm PST. Please fill this form to register for our event: http://bit.ly/HfLA-UX

**Comment by tan-zhou** [comment]
> @tan-zhou @rjdoria @rfambro2 Is anyone able to help with posting of this message in [the pipelines](https://docs.google.com/spreadsheets/d/1TuDelZ_pCg1pc9murZaYMsnv7CgEwXvoVtH5Jkt32XM/edit#gid=0)? We urgently need to start the UX recruitment process and it would be good for this to go out sooner than later. Please let me know asap if you will be taking this on.
> 
> (Volunteer Opportunity) Hi UX Researchers, UX Analysts and UX Program Designers! Hack for LA (https://hackforla.org/) is looking for people to work on civic tech projects. Come volunteer with us as we attempt to change the world one project at a time. There are both junior and senior roles available for you to contribute to meaningful projects. You don't have to be based in LA as we are operating remotely and welcome talent from around the world. Our next onboarding is Friday 2/12 from 12 - 2 pm PST. See this link http://bit.ly/HfLA-UX to find out about the roles available and register for our event:

I can post them.

**Comment by tan-zhou** [comment]
So far I've only able to post it in "Designership" slack channel while I'm waiting for my joining requests to be approved by the other groups. @rfambro2 Ray, were to able to join these groups when you did the last round of UX recruiting?

**Comment by rfambro2** [comment]
@tan-zhou - Hey Tan. I joined the Marketing Slack groups and did outreach for that effort. I also did something similar in Product Manager groups. But I believe Snigda was the one that did outreach for the UX/UI pipeline. Definitely can help in sending out the message though. I'm a part of a Slack group called "Where are the Black Designers?" - just posted it there now.

**Comment by tan-zhou** [comment]
Thanks @rfambro2 for posting. I've posted in three other slack groups that I'm in last night. Going to add the names in the pipeline. Looks like maybe we need to add a column in the pipeline that describes the length of the joining process, you think?

**Comment by rfambro2** [comment]
@tan-zhou - I just added the Recruitment Pipeline doc to this issue in the Resources section for easier coordination/access. We could potentially add that column...but I think the ultimate purpose for this information is just to track the outreach pipelines. I feel like the "Self Join" column addresses whether or not it's an automatic joining process, right?

**Comment by tan-zhou** [comment]
We've got 60 new responses for Friday's UX onboarding 🙌 Now hopefully we can get some great matches for the opening role. Let's go over the response list briefly at the meeting. In case someone doesn't get matched with a project, they should join the UX community of practice. Do you have enough good first issue for them to work on?

**Comment by tan-zhou** [comment]
@ExperimentsInHonesty is going to lead new UX people in a separate room for a first coaching session at Monday's community of practice meeting.

**Comment by rfambro2** [comment]
@tan-zhou - Should we close this issue? I think the comments we are adding now are steps beyond the initial task which was to get feedback from Mari. Maybe we should create/open a new issue for additional items to track.

**Comment by rfambro2** [comment]
@tan-zhou - We opened Issue #141 to start the procedure documentation for publicizing open roles

**Comment by tan-zhou** [comment]
> @tan-zhou
> 
> * We opened Issue #141 to start the procedure documentation for publicizing open roles
> * We opened Issue #142 to track the prep process for the UI/UX CoP board
> 
> Additional Notes:
> 
> * [ ]  Add column to pipeline spreadsheet for length of join process

Thank you for opening the issues. I think we are ready to close this one and address those parts of recruiting & onboarding.
